version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=cuidar
      - POSTGRES_USER=cuidarapiuser 
      - POSTGRES_DB=cuidardbdev
    ports:
      - '5432:5432'
    expose:
      - '5432'